spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment_db
    username: ${DB_USER:payment}
    password: ${DB_PASSWORD:payment}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8081}
